/**
 * Fee Revenue Model
 * 
 * Uniswap V3 fee calculation:
 * - Each swap pays a fee (e.g., 0.30% for 3000 bps tier)
 * - Fees are accrued to liquidity providers proportionally
 * - Your fee share = (your_liquidity / pool_liquidity) * fees_in_range
 * 
 * Fee tiers:
 * - 100 bps (0.01%): Stablecoin pairs, lowest IL, lowest fees
 * - 500 bps (0.05%): Stablecoin pairs, moderate
 * - 3000 bps (0.30%): Standard tier for most pairs
 * - 10000 bps (1.00%): Exotic pairs, highest fees, highest IL risk
 * 
 * Key formulas:
 * - fee_rate = fee_tier / 1000000 (e.g., 3000/1000000 = 0.003)
 * - fees_per_day = volume_24h * fee_rate * (your_liquidity / pool_liquidity)
 * - time_in_range_factor = probability of price staying in range
 */

/**
 * Fee tier descriptor
 */
export interface FeeTier {
  /** Basis points (100 = 0.01%, 3000 = 0.30%) */
  bps: number;
  /** Human readable label */
  label: string;
  /** Typical use case */
  description: string;
  /** Recommended for pairs with this vol profile */
  recommendedVol: 'low' | 'medium' | 'high';
}

/** All supported fee tiers */
export const FEE_TIERS: FeeTier[] = [
  {
    bps: 100,
    label: '0.01%',
    description: 'Lowest fee tier. Best for stablecoin-stablecoin pairs.',
    recommendedVol: 'low',
  },
  {
    bps: 500,
    label: '0.05%',
    description: 'Low-moderate fee. Good for correlated assets.',
    recommendedVol: 'low',
  },
  {
    bps: 3000,
    label: '0.30%',
    description: 'Standard Uniswap V3 tier. Default for most volatile pairs.',
    recommendedVol: 'medium',
  },
  {
    bps: 10000,
    label: '1.00%',
    description: 'High fee. For exotic or low-liquidity pairs.',
    recommendedVol: 'high',
  },
];

/**
 * Fee estimate result
 */
export interface FeeEstimate {
  /** Volume-based fee scenarios */
  lowVolume: number;    // pessimistic (25th percentile volume)
  baseVolume: number;   // expected (median volume)
  highVolume: number;    // optimistic (75th percentile volume)
  
  /** Assumptions used */
  volume24h: number;     // input volume used for base
  feeTier: number;       // input fee tier
  liquidity: number;      // pool TVL at calculation time
  timeInRange: number;   // decimal 0-1
  
  /** Fee breakdown */
  grossFees: number;     // total fees before protocol cut
  protocolFees: number; // Uniswap protocol fee (none currently on V3)
  netFees: number;       // your share of fees
  
  /** APR estimates */
  aprLow: number;        // APR at low volume scenario
  aprBase: number;       // APR at base volume scenario  
  aprHigh: number;       // APR at high volume scenario
}

/**
 * Calculate fee estimates for different volume scenarios.
 * 
 * @param params - fee calculation parameters
 * @param params.volume24h - 24h trading volume in USD
 * @param params.feeTier - fee tier in bps (100, 500, 3000, 10000)
 * @param params.liquidity - total pool TVL in USD
 * @param params.yourLiquidity - your position liquidity/value in USD
 * @param params.timeHorizonHours - time period for estimate (typically 24 for daily)
 * @param params.timeInRangePercent - probability/time fraction price is in range (0-1)
 * @returns FeeEstimate with scenarios and breakdown
 */
export function estimateFees(params: {
  volume24h: number;
  feeTier: number;
  liquidity: number;
  yourLiquidity: number;
  timeHorizonHours: number;
  timeInRangePercent: number;
}): FeeEstimate {
  
  const {
    volume24h,
    feeTier,
    liquidity,
    yourLiquidity,
    timeHorizonHours,
    timeInRangePercent,
  } = params;
  
  if (liquidity <= 0 || yourLiquidity <= 0) {
    return createZeroFeeEstimate(params);
  }
  
  // Fee rate as decimal
  const feeRate = feeTier / 1000000;
  
  // Your share of pool liquidity
  const liquidityShare = yourLiquidity / liquidity;
  
  // Time-weighted in-range factor
  // If you're in range 50% of the time, you earn 50% of full fees
  const effectiveTimeInRange = Math.min(1, timeInRangePercent);
  
  // Volume scenarios (±30% from base)
  const volumeLow = volume24h * 0.7;
  const volumeHigh = volume24h * 1.3;
  
  // Scale to time horizon
  const hoursScale = timeHorizonHours / 24;
  
  // Calculate fees for each scenario
  const calcFees = (vol: number): number => {
    const rawFees = vol * feeRate;
    const yourShare = rawFees * liquidityShare;
    const inRangeFees = yourShare * effectiveTimeInRange;
    return inRangeFees * hoursScale;
  };
  
  const lowVolumeFees = calcFees(volumeLow);
  const baseVolumeFees = calcFees(volume24h);
  const highVolumeFees = calcFees(volumeHigh);
  
  // Total fees generated by pool in this period
  const grossFees = volume24h * feeRate * hoursScale;
  const protocolFees = 0; // Uniswap V3 has no protocol fee
  const netFees = grossFees; // Full fees go to LPs
  
  // APR calculation (annualized)
  const hoursPerYear = 8760;
  const aprLow = baseVolumeFees > 0 
    ? (lowVolumeFees / yourLiquidity) * (hoursPerYear / timeHorizonHours) 
    : 0;
  const aprBase = baseVolumeFees > 0 
    ? (baseVolumeFees / yourLiquidity) * (hoursPerYear / timeHorizonHours) 
    : 0;
  const aprHigh = baseVolumeFees > 0 
    ? (highVolumeFees / yourLiquidity) * (hoursPerYear / timeHorizonHours) 
    : 0;
  
  return {
    lowVolume: lowVolumeFees,
    baseVolume: baseVolumeFees,
    highVolume: highVolumeFees,
    volume24h,
    feeTier,
    liquidity,
    timeInRange: effectiveTimeInRange,
    grossFees,
    protocolFees,
    netFees,
    aprLow: Math.min(10, aprLow),  // Cap at 1000% for sanity
    aprBase: Math.min(10, aprBase),
    aprHigh: Math.min(10, aprHigh),
  };
}

/**
 * Calculate time-in-range probability using a log-normal price model.
 * 
 * This estimates the probability that a price starting at currentPrice
 * stays within [lowerPrice, upperPrice] over a given time horizon.
 * 
 * Uses the formula for a log-normal diffusion:
 * P(in_range) = N((ln(U/S) + σ²T/2) / (σ√T)) - N((-σ√T/2) / (σ√T))
 * 
 * Simplified approximation suitable for trading ranges.
 * 
 * @param currentPrice - current price (token1/token0)
 * @param lowerPrice - lower bound price
 * @param upperPrice - upper bound price
 * @param volatilityDaily - daily volatility (e.g., 0.03 for 3%)
 * @param days - number of days to simulate
 * @returns probability that price stays in range (0-1)
 */
export function estimateTimeInRange(
  currentPrice: number,
  lowerPrice: number,
  upperPrice: number,
  volatilityDaily: number,
  days: number
): number {
  
  if (currentPrice <= 0 || lowerPrice <= 0 || upperPrice <= 0) {
    throw new Error('Prices must be positive');
  }
  
  if (lowerPrice >= upperPrice) {
    throw new Error('Lower price must be less than upper price');
  }
  
  if (volatilityDaily < 0) {
    throw new Error('Volatility must be non-negative');
  }
  
  // Quick checks
  if (currentPrice < lowerPrice) return 0;
  if (currentPrice > upperPrice) return 0;
  
  // Annualized volatility
  const volAnnual = volatilityDaily * Math.sqrt(365);
  const volSqrtT = volAnnual * Math.sqrt(days / 365);
  
  if (volSqrtT === 0) {
    // No volatility = deterministic path
    return currentPrice >= lowerPrice && currentPrice <= upperPrice ? 1 : 0;
  }
  
  // Log-normal parameters
  const mu = 0; // Assume zero drift for short horizons
  
  // Standard deviation of log returns over the period
  const sigma = volSqrtT;
  
  // Using standard log-normal barrier probability formula
  // P(S_T < U) = N((ln(U/S0) - μT) / σ√T)
  // P(S_T > L) = 1 - N((ln(L/S0) - μT) / σ√T)
  // P(L < S_T < U) = P(S_T < U) - P(S_T <= L)
  
  const lnUpper = Math.log(upperPrice / currentPrice);
  const lnLower = Math.log(lowerPrice / currentPrice);
  
  // CDF of standard normal
  const normCDF = (x: number): number => {
    // Approximation using error function
    return 0.5 * (1 + erf(x / Math.sqrt(2)));
  };
  
  const probBelowUpper = normCDF((lnUpper - mu * (days / 365)) / sigma);
  const probBelowLower = normCDF((lnLower - mu * (days / 365)) / sigma);
  
  const probInRange = probBelowUpper - probBelowLower;
  
  return Math.max(0, Math.min(1, probInRange));
}

/**
 * Calculate the expected time-in-range over multiple periods.
 * More accurate for longer horizons with mean-reversion.
 * 
 * @param currentPrice - current price
 * @param lowerPrice - lower bound
 * @param upperPrice - upper bound
 * @param volatilityDaily - daily volatility
 * @param days - total days
 * @param meanReversionStrength - strength of mean reversion (0-1, 0 = random walk)
 * @param meanPrice - long-term mean price (default = midpoint of range)
 */
export function estimateTimeInRangeWithReversion(
  currentPrice: number,
  lowerPrice: number,
  upperPrice: number,
  volatilityDaily: number,
  days: number,
  meanReversionStrength: number = 0,
  meanPrice?: number
): number {
  
  const mid = meanPrice ?? (lowerPrice + upperPrice) / 2;
  const rangeWidth = upperPrice - lowerPrice;
  
  // Simple mean-reversion simulation
  // Each day, price tends toward mean by meanReversionStrength
  let price = currentPrice;
  let daysInRange = 0;
  
  const dt = 1; // 1 day steps
  const volDaily = volatilityDaily;
  
  for (let d = 0; d < days; d++) {
    // Check if in range
    if (price >= lowerPrice && price <= upperPrice) {
      daysInRange++;
    }
    
    // Random walk step
    const randomShock = (Math.random() - 0.5) * 2 * volDaily * price;
    
    // Mean reversion pull
    const reversionPull = meanReversionStrength * (mid - price);
    
    price = price + reversionPull * dt + randomShock;
  }
  
  // Final check
  if (price >= lowerPrice && price <= upperPrice) {
    daysInRange++;
  }
  
  return daysInRange / (days + 1);
}

/**
 * Calculate optimal fee tier based on pair volatility.
 * 
 * Rule of thumb: fee should approximately equal expected IL for a day
 * This ensures fees cover IL and provide positive expected value.
 * 
 * @param dailyVolatility - daily price volatility (e.g., 0.02 for 2%)
 * @param correlation - asset correlation (for similar assets, use lower fees)
 * @returns recommended fee tier in bps
 */
export function suggestFeeTier(
  dailyVolatility: number,
  correlation: number = 0
): number {
  
  // Expected IL for a full-range position over one day ≈ vol^2 / 2
  const expectedIL = (dailyVolatility * dailyVolatility) / 2;
  
  // Fee tier that compensates for this IL
  // We want fee ≈ IL * some_factor (1.5-2x for profit)
  const targetFee = expectedIL * 1.5;
  
  // Map to nearest fee tier
  const tiers = [100, 500, 3000, 10000];
  const tierFeeRates = tiers.map(t => t / 1000000);
  
  // Find tier closest to target
  let closestTier = 3000;
  let minDiff = Infinity;
  
  for (let i = 0; i < tiers.length; i++) {
    const diff = Math.abs(tierFeeRates[i] - targetFee);
    if (diff < minDiff) {
      minDiff = diff;
      closestTier = tiers[i];
    }
  }
  
  // Adjust for correlation (correlated pairs have less IL, can use lower fees)
  if (correlation > 0.8) {
    closestTier = Math.min(closestTier, 500);
  } else if (correlation > 0.5) {
    closestTier = Math.min(closestTier, 3000);
  }
  
  return closestTier;
}

/**
 * Calculate how fees scale with position size (returns to scale).
 * Larger positions may face more slippage in rebalancing.
 * 
 * @param yourLiquidity - your position size in USD
 * @param poolLiquidity - total pool liquidity in USD
 * @param volume24h - 24h volume in USD
 * @returns effective fee multiplier (1 = no impact, <1 = reduced fees)
 */
export function calculateFeeSlippageImpact(
  yourLiquidity: number,
  poolLiquidity: number,
  volume24h: number
): number {
  
  if (poolLiquidity === 0) return 0;
  
  // Your share of the pool
  const share = yourLiquidity / poolLiquidity;
  
  // If you represent >10% of pool, you may impact price
  // This affects fee generation efficiency
  if (share < 0.1) return 1;
  
  // Linear reduction as share grows
  // At 50% share, your fees are effectively halved due to self-trading
  const impact = Math.max(0.1, 1 - share);
  
  return impact;
}

// ─────────────────────────────────────────────────────────────────────────────
// HELPERS
// ─────────────────────────────────────────────────────────────────────────────

/**
 * Error function approximation using the CERF algorithm.
 */
function erf(x: number): number {
  // Approximation taken from Numerical Recipes
  const t = 1 / (1 + 0.5 * Math.abs(x));
  const tau = t * Math.exp(-x * x - 1.26551223 +
    t * (1.00002368 +
    t * (0.37409196 +
    t * (0.09678418 +
    t * (-0.18628806 +
    t * (0.27886807 +
    t * (-1.13520398 +
    t * (1.48851587 +
    t * (-0.82215223 +
    t * 0.17087277)))))))));
  
  return x >= 0 ? 1 - tau : tau - 1;
}

/**
 * Create a zero/empty fee estimate.
 */
function createZeroFeeEstimate(params: {
  volume24h: number;
  feeTier: number;
  liquidity: number;
  yourLiquidity: number;
  timeHorizonHours: number;
  timeInRangePercent: number;
}): FeeEstimate {
  return {
    lowVolume: 0,
    baseVolume: 0,
    highVolume: 0,
    volume24h: params.volume24h,
    feeTier: params.feeTier,
    liquidity: params.liquidity,
    timeInRange: 0,
    grossFees: 0,
    protocolFees: 0,
    netFees: 0,
    aprLow: 0,
    aprBase: 0,
    aprHigh: 0,
  };
}
