/**
 * Uniswap V3 Fee Calculations
 * 
 * This module implements fee estimation models for Uniswap V3 LP positions.
 */

import { FeeEstimateParams, FeeEstimateResult } from '@/types';

/**
 * Estimate fees for an LP position based on volume assumptions
 * @param params - Fee estimation parameters
 * @returns Fee estimate with min/base/max values
 */
export function estimateFees(params: FeeEstimateParams): FeeEstimateResult {
  const {
    dailyVolumeUSD,
    volumeScenario,
    customVolumeMultiplier = 1,
    feeTier,
    positionLiquidity,
    activeLiquidityInRange,
    timeInRange,
    horizonDays,
  } = params;

  // Volume multipliers for different scenarios
  const volumeMultipliers: Record<string, number> = {
    low: 0.5,
    base: 1.0,
    high: 2.0,
    custom: customVolumeMultiplier,
  };

  const multiplier = volumeMultipliers[volumeScenario] ?? 1.0;
  const adjustedDailyVolume = dailyVolumeUSD * multiplier;

  // Calculate daily fees generated by the pool
  const feeRate = feeTier / 1_000_000; // Convert basis points to decimal
  const dailyPoolFees = adjustedDailyVolume * feeRate;

  // Calculate position's share of fees
  // If position is the only liquidity in range, it gets 100%
  // Otherwise, it's proportional to liquidity share
  const liquidityShare = activeLiquidityInRange > 0n
    ? Number(positionLiquidity) / Number(activeLiquidityInRange)
    : 0;

  // Apply time-in-range factor
  const effectiveShare = liquidityShare * timeInRange;

  // Calculate daily fees for the position
  const dailyPositionFees = dailyPoolFees * effectiveShare;

  // Calculate total fees over the horizon
  const totalFees = dailyPositionFees * horizonDays;

  // Calculate confidence intervals based on scenario
  let min: number;
  let max: number;
  
  switch (volumeScenario) {
    case 'low':
      min = totalFees * 0.7;
      max = totalFees * 1.3;
      break;
    case 'high':
      min = totalFees * 0.8;
      max = totalFees * 1.2;
      break;
    case 'custom':
      min = totalFees * 0.6;
      max = totalFees * 1.4;
      break;
    case 'base':
    default:
      min = totalFees * 0.5;
      max = totalFees * 1.5;
      break;
  }

  return {
    min: Math.max(0, min),
    base: totalFees,
    max: Math.max(0, max),
    confidenceInterval: [min, max],
  };
}

/**
 * Calculate fee APR from volume and TVL
 * @param volumeUSD24h - 24-hour volume in USD
 * @param tvlUSD - Total value locked in USD
 * @param feeTier - Pool fee tier in basis points
 * @returns Annualized fee APR as decimal
 */
export function calculateFeeAPR(
  volumeUSD24h: number,
  tvlUSD: number,
  feeTier: number
): number {
  if (tvlUSD === 0) return 0;

  const feeRate = feeTier / 1_000_000;
  const dailyFees = volumeUSD24h * feeRate;
  const dailyAPR = dailyFees / tvlUSD;
  const annualAPR = dailyAPR * 365;

  return annualAPR;
}

/**
 * Estimate position's share of pool fees
 * @param positionLiquidity - Position liquidity amount
 * @param activeLiquidity - Active liquidity in range
 * @param poolFees24h - Pool fees in last 24h
 * @returns Position's estimated fee earnings
 */
export function estimatePositionFeeShare(
  positionLiquidity: bigint,
  activeLiquidity: bigint,
  poolFees24h: number
): number {
  if (activeLiquidity === 0n) return 0;

  const share = Number(positionLiquidity) / Number(activeLiquidity);
  return poolFees24h * share;
}

/**
 * Calculate break-even volume for a position
 * @param targetFees - Target fee earnings
 * @param feeTier - Pool fee tier
 * @param liquidityShare - Position's liquidity share
 * @returns Required daily volume
 */
export function calculateBreakEvenVolume(
  targetFees: number,
  feeTier: number,
  liquidityShare: number,
  horizonDays: number
): number {
  if (liquidityShare === 0 || feeTier === 0) return Infinity;

  const feeRate = feeTier / 1_000_000;
  const dailyTargetFees = targetFees / horizonDays;
  const dailyPoolFeesNeeded = dailyTargetFees / liquidityShare;

  return dailyPoolFeesNeeded / feeRate;
}

/**
 * Analyze fee competitiveness
 * @param poolFeeAPR - Pool's fee APR
 * @param competitorAPRs - Array of competitor pool APRs
 * @returns Competitiveness analysis
 */
export function analyzeFeeCompetitiveness(
  poolFeeAPR: number,
  competitorAPRs: number[]
): {
  rank: number;
  percentile: number;
  isCompetitive: boolean;
} {
  const allAPRs = [poolFeeAPR, ...competitorAPRs];
  const sortedAPRs = allAPRs.sort((a, b) => b - a);
  const rank = sortedAPRs.indexOf(poolFeeAPR) + 1;
  const percentile = ((competitorAPRs.length - rank + 1) / competitorAPRs.length) * 100;

  return {
    rank,
    percentile,
    isCompetitive: percentile >= 50,
  };
}

/**
 * Estimate fees with liquidity competition
 * @param params - Base fee parameters
 * @param competitorLiquidity - Array of competitor liquidities
 * @returns Adjusted fee estimate
 */
export function estimateFeesWithCompetition(
  params: FeeEstimateParams,
  competitorLiquidity: bigint[]
): FeeEstimateResult {
  const totalCompetitorLiquidity = competitorLiquidity.reduce(
    (sum, liq) => sum + liq,
    0n
  );

  const totalLiquidity = params.activeLiquidityInRange + totalCompetitorLiquidity;

  const adjustedParams = {
    ...params,
    activeLiquidityInRange: totalLiquidity,
  };

  return estimateFees(adjustedParams);
}

/**
 * Calculate fee APY with compounding
 * @param apr - Annual percentage rate
 * @param compoundingPeriods - Number of compounding periods per year
 * @returns APY as decimal
 */
export function calculateFeeAPY(
  apr: number,
  compoundingPeriods: number = 365
): number {
  return Math.pow(1 + apr / compoundingPeriods, compoundingPeriods) - 1;
}

/**
 * Project fees over time
 * @param initialDailyVolume - Starting daily volume
 * @param volumeGrowthRate - Daily volume growth rate
 * @param feeTier - Pool fee tier
 * @param liquidityShare - Position's liquidity share
 * @param days - Number of days to project
 * @returns Array of daily fee projections
 */
export function projectFeesOverTime(
  initialDailyVolume: number,
  volumeGrowthRate: number,
  feeTier: number,
  liquidityShare: number,
  days: number
): Array<{ day: number; volume: number; fees: number }> {
  const feeRate = feeTier / 1_000_000;
  const projections = [];

  for (let day = 0; day < days; day++) {
    const volume = initialDailyVolume * Math.pow(1 + volumeGrowthRate, day);
    const poolFees = volume * feeRate;
    const positionFees = poolFees * liquidityShare;

    projections.push({
      day,
      volume,
      fees: positionFees,
    });
  }

  return projections;
}

/**
 * Calculate impermanent loss offset by fees
 * @param ilPercent - Impermanent loss percentage
 * @param feeAPR - Fee APR
 * @param timeDays - Time period in days
 * @returns Net return after fees offset IL
 */
export function calculateNetReturnAfterFees(
  ilPercent: number,
  feeAPR: number,
  timeDays: number
): number {
  const feeReturn = feeAPR * (timeDays / 365);
  return feeReturn - ilPercent;
}

/**
 * Estimate time to break-even
 * @param entryPrice - Entry price
 * @param lowerPrice - Lower bound price
 * @param upperPrice - Upper bound price
 * @param feeAPR - Fee APR
 * @returns Days to break-even or null if never
 */
export function estimateTimeToBreakeven(
  entryPrice: number,
  lowerPrice: number,
  upperPrice: number,
  feeAPR: number
): number | null {
  // Estimate max IL at range boundaries
  const maxPriceMove = Math.max(
    Math.abs(entryPrice - lowerPrice) / entryPrice,
    Math.abs(entryPrice - upperPrice) / entryPrice
  );

  // Approximate max IL (simplified)
  const maxIL = maxPriceMove * 0.25; // Rough approximation

  if (feeAPR === 0) return null;

  const daysToBreakeven = (maxIL / feeAPR) * 365;
  return Math.ceil(daysToBreakeven);
}
